on: push
name: Build on push
jobs:
  npmTest:
    name: npm test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: npm run build
      uses: actions/npm@master
      with:
        args: run build
    - name: npm run lint
      uses: actions/npm@master
      with:
        args: run lint
    - name: npm test
      uses: actions/npm@master
      with:
        args: test -- --coverage
    - name: npm run codecov
      uses: actions/npm@master
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        args: run codecov -- --token="$CODECOV_TOKEN"
    - name: tag
      uses: actions/bin/filter@master
      with:
        args: tag
    - name: npm publish
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish--access public
