on: push
name: Build and publish on push
jobs:
  npmBuildTestPublish:
    name: Build, test, lint and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: build
      uses: actions/npm@master
      with:
        args: run build
    - name: run linting checks
      uses: actions/npm@master
      with:
        args: run lint
    - name: run tests
      uses: actions/npm@master
      with:
        args: test -- --coverage
    - name: publish code coverage report to codecov
      uses: actions/npm@master
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        args: run codecov -- --token="$CODECOV_TOKEN"
    - name: npm publish (if tag was created)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish --access public
